import SwiftUI
import Amplify
import AWSCognitoAuthPlugin
import AWSAPIPlugin

@main
struct My_LifestyleApp: App {
    init() {
        Self.configureAmplify()
    }

    var body: some Scene {
        WindowGroup {
            MainTabView()
        }
    }

    /// Registers the Auth (Cognito) and API (AppSync) plugins and configures
    /// Amplify from the bundled `amplify_outputs.json` generated by the
    /// Amplify Gen 2 sandbox.
    private static func configureAmplify() {
        do {
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.add(plugin: AWSAPIPlugin())
            try Amplify.configure(with: .amplifyOutputs)
            print("Amplify configured successfully")
        } catch {
            print("Failed to configure Amplify: \(error)")
        }
    }
}
